### ISSUE TITLE
Failed to load the linter-hdevtools package

### ISSUE THREAD

**Issue by raduom** [ranjitjhala/linter-hdevtools#3]
[Enter steps to reproduce below:]
1. Upgrade to the latest version of the package.

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [linter-hdevtools](https://github.com/ranjitjhala/linter-hdevtools) package, v1.2.0
### Stack Trace

Failed to load the linter-hdevtools package

```
At Cannot find module 'xregexp'

Error: Cannot find module 'xregexp'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/roa/.atom/packages/linter-hdevtools/lib/init.coffee:6:13)
    at Object.<anonymous> (/Users/roa/.atom/packages/linter-hdevtools/lib/init.coffee:119:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-hlint",
      "hover-tooltips-hdevtools"
    ]
  },
  "linter-hdevtools": {
    "hdevtoolsExecutablePath": "/Users/roa/.cabal/bin"
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-haskell, v0.4.5
haskell-ghc-mod, v0.8.3
ide-haskell, v0.6.2
language-haskell, v1.2.0
linter, v1.2.4
linter-hdevtools, v1.2.0

# Dev
No dev packages
```

**Comment by ranjitjhala** [comment]
Oops!y apologies I am new to npm dependencies. In the short term can you do 

npm install -g xregexp

While I fix this?

**Comment by ranjitjhala** [comment]
Hi, sorry about that again! Can you try to upgrade to version 1.3.0. It _should_ fix the problem...

**Comment by raduom** [comment]
Hi. The problem is fixed, however another thing popped out. This sequence of actions produces a 
Failed to run undefined 
spawn EACCES
1. Disable linter-hdevtools
2. Restart atom
3. Enable linter-hdevtools
4. Restart atom -> Exception.

It may be due to some local problems, but if I disable the linter-hdevtools plugin the error goes away.
And I have been meaning to thank you for the quick response. Much appreciated!

**Comment by ranjitjhala** [comment]
Whoa! That's odd. Does the problem persist if you
1. restart atom?
2. do a "killall hdevtools" at the shell?

**Comment by raduom** [comment]
It was due to me starting atom from the Spotlight Search. I am assuming that it can't find the path to something. It seems to be working ok if i start it from command line.

**Comment by raduom** [comment]
1. Not working
2. No hdevtools is started (even when running atom, could this be it?).

**Comment by raduom** [comment]
It was not finding the path to hdevtools. I provided only the directory path, without the hdevtools binary name. Fixed now. Thanks for all the help.

**Comment by ranjitjhala** [comment]
Great, glad it got sorted out! (I will add a note to the README to mention
the above.)
